### Добавление Марселя

POST localhost:8080/api/users
Content-Type: application/json

{
  "email": "sidikov.m@gmail.com",
  "password": "qwerty007",
  "firstName": "Marsel",
  "lastName": "Sidikov"
}

### Добавление Алишера

POST localhost:8080/api/users
Content-Type: application/json

{
  "email": "alisher@gmail.com",
  "password": "qwerty008",
  "firstName": "Alisher",
  "lastName": "Khamidov"
}

### Получение всех пользователей

GET localhost:8080/api/users